name: CI

on:
  push:
    branches: [main]

jobs:
  exo:
    runs-on: ubuntu-latest

    steps:
      - name: Annonce
        run: echo "Le restaurant est ouvert !"

      - name: Initialiser npm
        run: npm init -y
      
      - name: Installer jest
        run: npm install --save-dev jest

        