name: CI

on:
  push:
    branches: [main]

jobs:
  runs-on: ubuntu-latest

  sterps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Annonce
      run: echo"Le restaurant est ouvert !"